version: '3'

services:
  db:
    image: newsfeed-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - <Absolute path to data directory>:/var/lib/mysql